export const tokenAbi = [
    {
        type: 'constructor',
        inputs: [{ name: '_manager', internalType: 'address', type: 'address' }],
        stateMutability: 'payable',
    },
    { type: 'error', inputs: [], name: 'ADDRESS_ZERO' },
    { type: 'error', inputs: [], name: 'ALREADY_INITIALIZED' },
    { type: 'error', inputs: [], name: 'ALREADY_MINTED' },
    { type: 'error', inputs: [], name: 'CANNOT_CHANGE_RESERVE' },
    { type: 'error', inputs: [], name: 'CANNOT_DECREASE_RESERVE' },
    { type: 'error', inputs: [], name: 'DELEGATE_CALL_FAILED' },
    { type: 'error', inputs: [], name: 'EXPIRED_SIGNATURE' },
    { type: 'error', inputs: [], name: 'INITIALIZING' },
    { type: 'error', inputs: [], name: 'INVALID_APPROVAL' },
    { type: 'error', inputs: [], name: 'INVALID_FOUNDER_OWNERSHIP' },
    { type: 'error', inputs: [], name: 'INVALID_OWNER' },
    { type: 'error', inputs: [], name: 'INVALID_RECIPIENT' },
    { type: 'error', inputs: [], name: 'INVALID_SIGNATURE' },
    { type: 'error', inputs: [], name: 'INVALID_TARGET' },
    { type: 'error', inputs: [], name: 'INVALID_TIMESTAMP' },
    {
        type: 'error',
        inputs: [{ name: 'impl', internalType: 'address', type: 'address' }],
        name: 'INVALID_UPGRADE',
    },
    { type: 'error', inputs: [], name: 'NOT_INITIALIZING' },
    { type: 'error', inputs: [], name: 'NOT_MINTED' },
    { type: 'error', inputs: [], name: 'NO_METADATA_GENERATED' },
    { type: 'error', inputs: [], name: 'ONLY_AUCTION' },
    { type: 'error', inputs: [], name: 'ONLY_AUCTION_OR_MINTER' },
    { type: 'error', inputs: [], name: 'ONLY_CALL' },
    { type: 'error', inputs: [], name: 'ONLY_DELEGATECALL' },
    { type: 'error', inputs: [], name: 'ONLY_MANAGER' },
    { type: 'error', inputs: [], name: 'ONLY_OWNER' },
    { type: 'error', inputs: [], name: 'ONLY_PENDING_OWNER' },
    { type: 'error', inputs: [], name: 'ONLY_PROXY' },
    { type: 'error', inputs: [], name: 'ONLY_TOKEN_OWNER' },
    { type: 'error', inputs: [], name: 'ONLY_UUPS' },
    { type: 'error', inputs: [], name: 'REENTRANCY' },
    { type: 'error', inputs: [], name: 'TOKEN_NOT_RESERVED' },
    { type: 'error', inputs: [], name: 'UNSUPPORTED_UUID' },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'owner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'approved',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'tokenId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: true,
            },
        ],
        name: 'Approval',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'owner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'operator',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
        ],
        name: 'ApprovalForAll',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'delegator',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            { name: 'from', internalType: 'address', type: 'address', indexed: true },
            { name: 'to', internalType: 'address', type: 'address', indexed: true },
        ],
        name: 'DelegateChanged',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'delegate',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'prevTotalVotes',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: 'newTotalVotes',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'DelegateVotesChanged',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'newFounders',
                internalType: 'struct IManager.FounderParams[]',
                type: 'tuple[]',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint256', type: 'uint256' },
                    { name: 'vestExpiry', internalType: 'uint256', type: 'uint256' },
                ],
                indexed: false,
            },
        ],
        name: 'FounderAllocationsCleared',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'version',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'Initialized',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'renderer',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
        ],
        name: 'MetadataRendererUpdated',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'baseTokenId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: 'founderId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: 'founder',
                internalType: 'struct TokenTypesV1.Founder',
                type: 'tuple',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint8', type: 'uint8' },
                    { name: 'vestExpiry', internalType: 'uint32', type: 'uint32' },
                ],
                indexed: false,
            },
        ],
        name: 'MintScheduled',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'baseTokenId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: 'founderId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
            {
                name: 'founder',
                internalType: 'struct TokenTypesV1.Founder',
                type: 'tuple',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint8', type: 'uint8' },
                    { name: 'vestExpiry', internalType: 'uint32', type: 'uint32' },
                ],
                indexed: false,
            },
        ],
        name: 'MintUnscheduled',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'minter',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
            { name: 'allowed', internalType: 'bool', type: 'bool', indexed: false },
        ],
        name: 'MinterUpdated',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'owner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'canceledOwner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
        ],
        name: 'OwnerCanceled',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'owner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'pendingOwner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
        ],
        name: 'OwnerPending',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'prevOwner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
            {
                name: 'newOwner',
                internalType: 'address',
                type: 'address',
                indexed: true,
            },
        ],
        name: 'OwnerUpdated',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'reservedUntilTokenId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: false,
            },
        ],
        name: 'ReservedUntilTokenIDUpdated',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            { name: 'from', internalType: 'address', type: 'address', indexed: true },
            { name: 'to', internalType: 'address', type: 'address', indexed: true },
            {
                name: 'tokenId',
                internalType: 'uint256',
                type: 'uint256',
                indexed: true,
            },
        ],
        name: 'Transfer',
    },
    {
        type: 'event',
        anonymous: false,
        inputs: [
            {
                name: 'impl',
                internalType: 'address',
                type: 'address',
                indexed: false,
            },
        ],
        name: 'Upgraded',
    },
    {
        type: 'function',
        inputs: [],
        name: 'DOMAIN_SEPARATOR',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'acceptOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_to', internalType: 'address', type: 'address' },
            { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'approve',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'auction',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_owner', internalType: 'address', type: 'address' }],
        name: 'balanceOf',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
        name: 'burn',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'cancelOwnershipTransfer',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'contractURI',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'contractVersion',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        inputs: [{ name: '_to', internalType: 'address', type: 'address' }],
        name: 'delegate',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_from', internalType: 'address', type: 'address' },
            { name: '_to', internalType: 'address', type: 'address' },
            { name: '_deadline', internalType: 'uint256', type: 'uint256' },
            { name: '_v', internalType: 'uint8', type: 'uint8' },
            { name: '_r', internalType: 'bytes32', type: 'bytes32' },
            { name: '_s', internalType: 'bytes32', type: 'bytes32' },
        ],
        name: 'delegateBySig',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '_account', internalType: 'address', type: 'address' }],
        name: 'delegates',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
        name: 'getApproved',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_founderId', internalType: 'uint256', type: 'uint256' }],
        name: 'getFounder',
        outputs: [
            {
                name: '',
                internalType: 'struct TokenTypesV1.Founder',
                type: 'tuple',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint8', type: 'uint8' },
                    { name: 'vestExpiry', internalType: 'uint32', type: 'uint32' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'getFounders',
        outputs: [
            {
                name: '',
                internalType: 'struct TokenTypesV1.Founder[]',
                type: 'tuple[]',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint8', type: 'uint8' },
                    { name: 'vestExpiry', internalType: 'uint32', type: 'uint32' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: '_account', internalType: 'address', type: 'address' },
            { name: '_timestamp', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'getPastVotes',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
        name: 'getScheduledRecipient',
        outputs: [
            {
                name: '',
                internalType: 'struct TokenTypesV1.Founder',
                type: 'tuple',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint8', type: 'uint8' },
                    { name: 'vestExpiry', internalType: 'uint32', type: 'uint32' },
                ],
            },
        ],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_account', internalType: 'address', type: 'address' }],
        name: 'getVotes',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            {
                name: '_founders',
                internalType: 'struct IManager.FounderParams[]',
                type: 'tuple[]',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint256', type: 'uint256' },
                    { name: 'vestExpiry', internalType: 'uint256', type: 'uint256' },
                ],
            },
            { name: '_initStrings', internalType: 'bytes', type: 'bytes' },
            {
                name: '_reservedUntilTokenId',
                internalType: 'uint256',
                type: 'uint256',
            },
            { name: '_metadataRenderer', internalType: 'address', type: 'address' },
            { name: '_auction', internalType: 'address', type: 'address' },
            { name: '_initialOwner', internalType: 'address', type: 'address' },
        ],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_owner', internalType: 'address', type: 'address' },
            { name: '_operator', internalType: 'address', type: 'address' },
        ],
        name: 'isApprovedForAll',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_minter', internalType: 'address', type: 'address' }],
        name: 'isMinter',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'metadataRenderer',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'mint',
        outputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: 'amount', internalType: 'uint256', type: 'uint256' },
            { name: 'recipient', internalType: 'address', type: 'address' },
        ],
        name: 'mintBatchTo',
        outputs: [
            { name: 'tokenIds', internalType: 'uint256[]', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: 'recipient', internalType: 'address', type: 'address' },
            { name: 'tokenId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'mintFromReserveTo',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: 'recipient', internalType: 'address', type: 'address' }],
        name: 'mintTo',
        outputs: [{ name: 'tokenId', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '', internalType: 'address', type: 'address' }],
        name: 'minter',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'name',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_account', internalType: 'address', type: 'address' }],
        name: 'nonce',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'onFirstAuctionStarted',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [],
        name: 'owner',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
        name: 'ownerOf',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'pendingOwner',
        outputs: [{ name: '', internalType: 'address', type: 'address' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'proxiableUUID',
        outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'remainingTokensInReserve',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'reservedUntilTokenId',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: '_from', internalType: 'address', type: 'address' },
            { name: '_to', internalType: 'address', type: 'address' },
            { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'safeTransferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_from', internalType: 'address', type: 'address' },
            { name: '_to', internalType: 'address', type: 'address' },
            { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
            { name: '_data', internalType: 'bytes', type: 'bytes' },
        ],
        name: 'safeTransferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '_newOwner', internalType: 'address', type: 'address' }],
        name: 'safeTransferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_operator', internalType: 'address', type: 'address' },
            { name: '_approved', internalType: 'bool', type: 'bool' },
        ],
        name: 'setApprovalForAll',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            {
                name: 'newRenderer',
                internalType: 'contract IBaseMetadata',
                type: 'address',
            },
        ],
        name: 'setMetadataRenderer',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            {
                name: 'newReservedUntilTokenId',
                internalType: 'uint256',
                type: 'uint256',
            },
        ],
        name: 'setReservedUntilTokenId',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '_interfaceId', internalType: 'bytes4', type: 'bytes4' }],
        name: 'supportsInterface',
        outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
        stateMutability: 'pure',
    },
    {
        type: 'function',
        inputs: [],
        name: 'symbol',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [{ name: '_tokenId', internalType: 'uint256', type: 'uint256' }],
        name: 'tokenURI',
        outputs: [{ name: '', internalType: 'string', type: 'string' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'totalFounderOwnership',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'totalFounders',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [],
        name: 'totalSupply',
        outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
        stateMutability: 'view',
    },
    {
        type: 'function',
        inputs: [
            { name: '_from', internalType: 'address', type: 'address' },
            { name: '_to', internalType: 'address', type: 'address' },
            { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
        ],
        name: 'transferFrom',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '_newOwner', internalType: 'address', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            {
                name: 'newFounders',
                internalType: 'struct IManager.FounderParams[]',
                type: 'tuple[]',
                components: [
                    { name: 'wallet', internalType: 'address', type: 'address' },
                    { name: 'ownershipPct', internalType: 'uint256', type: 'uint256' },
                    { name: 'vestExpiry', internalType: 'uint256', type: 'uint256' },
                ],
            },
        ],
        name: 'updateFounders',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            {
                name: '_minters',
                internalType: 'struct TokenTypesV2.MinterParams[]',
                type: 'tuple[]',
                components: [
                    { name: 'minter', internalType: 'address', type: 'address' },
                    { name: 'allowed', internalType: 'bool', type: 'bool' },
                ],
            },
        ],
        name: 'updateMinters',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [{ name: '_newImpl', internalType: 'address', type: 'address' }],
        name: 'upgradeTo',
        outputs: [],
        stateMutability: 'nonpayable',
    },
    {
        type: 'function',
        inputs: [
            { name: '_newImpl', internalType: 'address', type: 'address' },
            { name: '_data', internalType: 'bytes', type: 'bytes' },
        ],
        name: 'upgradeToAndCall',
        outputs: [],
        stateMutability: 'payable',
    },
] as const
